version: '3.9'

services:
#  api:
#    container_name: api
#    restart: unless-stopped
#    env_file: api.env
#    build:
#      context: ./api
#      dockerfile: app.dockerfile
#    depends_on:
#      - db
#    ports:
#      - 8000:8000
#
#  bot:
#    container_name: bot
#    restart: unless-stopped
#    env_file: api.env
#    build:
#      context: ./bot
#      dockerfile: bot.dockerfile
#    depends_on:
#      - api
#
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    restart: always
#    depends_on:
#      - api
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#      - /etc/letsencrypt:/etc/letsencrypt
#      - /var/www/html:/var/www/html
#    ports:
#      - 80:80
#      - 443:443

  db:
    container_name: database
    image: postgres:latest
    env_file: api/db.env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DBUSER} -d ${DBNAME}'" ]
      interval: 10s
      timeout: 3s
      retries: 10
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
